src/internal/global-utils.ts
src/internal/semver.ts
test/internal/semver.test.ts

The semver check is backwards. It has not yet caused a bug because we haven't released any other 0.18.x
In the current 0.18 semver check if the user registers a global with version 0.18.0, then API module 0.18.1 attempts to access it, it will succeed. 0.18.1 may attempt to call a method which doesn't exist on 0.18.0. It should be the other way around. 0.18.0 should be able to access the 0.18.1 global because that global has at least the methods 0.18.0 expects.
I caught this while testing the semver check with fake versioning in my sample project

fix: Reverse the direction of the semver check

---

package.json
tsconfig.esm.json

While typescript uses ESM syntax, the code distributed on npm (build dir) has been transpiled to use commonjs require's for better compatibility. However this means that bundlers like webpack and rollup can't do tree shaking to remove code not imported by user, leaving behind unused dead code.
While `@opentelemetry/api` has lesser tree shake potential [due to code with side effects](https://github.com/open-telemetry/opentelemetry-js-api/blob/504041a8aa8442987a95f675af0a402084678682/src/index.ts#L60), I figured the best way to tackle this is to first target the one package in it's own repo, and once good implementation is figured out copy it to packages in open-telemetry/opentelemetry-js and open-telemetry/opentelemetry-js-contrib.
Relevant:
open-telemetry/opentelemetry-js#1378 …

Add ESM build

---

src/api/context.ts
src/api/diag.ts
src/api/propagation.ts
src/api/trace.ts
src/internal/global-utils.ts

feat!: return boolean success value from setGlobalXXX methods

---

README.md

adding headline similar to core repo, fixing links

chore: updating readme headline and fixing links

---

README.md
src/context/context.ts
src/trace/NonRecordingSpan.ts
src/trace/NoopTracer.ts
test/api/api.test.ts
test/noop-implementations/noop-span.test.ts
test/noop-implementations/noop-tracer.test.ts
test/proxy-implementations/proxy-tracer.test.ts

Fixes https://github.com/open-telemetry/opentelemetry-js-api/issues/41

chore: renaming noop span to non recording span

---

src/api/trace.ts
src/index.ts
src/trace/spancontext-utils.ts
test/trace/spancontext-utils.test.ts

feat: add function to wrap SpanContext in NonRecordingSpan #49

---

README.md
src/api/propagation.ts
src/index.ts
test/baggage/Baggage.test.ts

Since we moved the span context method into `trace` namespace, i'm also proposing to move `[create/get/set]Baggage` into the `propagation` namespace.
We still export `baggageEntryMetadataFromString` which feels kinda wrong to me since it doesn't do anything apart creating a unusued object, could we have a less strict type for the metadata so we don't need this function ?

chore: move baggage methods in propagation namespace

---

src/trace/NoopTracer.ts
src/trace/ProxyTracer.ts
src/trace/tracer.ts
test/noop-implementations/noop-tracer.test.ts
test/proxy-implementations/proxy-tracer.test.ts

adds helper function tracer.startActiveSpan()  which creates a new span and activates it in the current Context

feat: add tracer.startActiveSpan()

---

src/api/propagation.ts
src/api/trace.ts
src/baggage/context-helpers.ts
src/trace/context-utils.ts

Ref: 
- https://github.com/open-telemetry/opentelemetry-js-api/issues/66
- https://github.com/open-telemetry/opentelemetry-js/pull/2185#discussion_r631128874
Fixes #66

feat(context): add utils method to remove keys from context #66

---

.github/workflows/test.yaml

Adds current node version(16) to the test matrix.
- https://github.com/open-telemetry/opentelemetry-js/pull/2244
- https://github.com/open-telemetry/opentelemetry-js-contrib/pull/510

chore: add node:16 to the test matrix

---

src/api/context.ts
src/context/NoopContextManager.ts
src/context/types.ts
test/context/NoopContextManager.test.ts

Just like `Function.prototype.apply`, `Function.prototype.call` and `Function.prototype.bind` have the same signature, it would make sense for `context.with` and `context.bind` to do the same to prevent confusion among the instrumentation developers(I know I have made the mistake a few times).
Having `context` as the first argument also makes intuitive sense, to me at least, even without considering the signature of `context.with` - probably because of how `Function.prototype.bind` works.
One drawback for this is the fact that the function argument to both of those methods is more "stable" - meaning that making the function an optional parameter makes no sense, but context, on the other hand, has an intuitive default: the active context. So:
```
api.context.bind(undefined, () => {
// …
```

feat: unify signatures of `with` and `bind`

---

src/api/context.ts
src/api/diag.ts
src/api/propagation.ts
src/api/trace.ts
src/internal/global-utils.ts

Fixes #87 
The `global-utils.ts` depends on the `diag` API, which depends on `global-utils`. This results in a circular dependency.
Resolve by injecting the `diag` instance into the function at call time.
/cc @MSNev

chore: remove circular dependency

---

src/trace/ProxyTracer.ts

Create a single `NoopTracer` and reuse it in `ProxyTracer` to avoid creation of a new `NoopTracer` on every `startSpan()` call in case no SDK is present.

chore: reuse NoopTracer in ProxyTracer

---

src/trace/tracer.ts

Example in documentation fro `tracer.startActiveSpan` is misformated:
That PR is gonna fix that:
I have doubts whether the second example - although technically correct - is optimal for promotion and indication in the documentation.

docs: Format example for tracer.startActiveSpan

---

README.md

When running the example in the README before this change I get:
```
% node --trace-warnings example.js
{
traceId: 'b0a511fe69ff65345b18db0486cb8568',
parentId: undefined,
name: 'do operation',
id: '0ccd8ba64328a259',
kind: 0,
timestamp: 1626991645695433,
duration: 1004811,
attributes: {},
status: { code: 0 },
events: []
}
(node:47750) UnhandledPromiseRejectionWarning: ReferenceError: output is not defined
at operation (/Users/trentm/tm/otelplay/example.js:24:3)
at async main (/Users/trentm/tm/otelplay/example.js:29:5)
at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
at processPromiseRejections (internal/process/promises.js:247:11)
at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:47750) ReferenceError: output is not defined
at operation …
```

docs: fix crash in README example

---

.github/CODEOWNERS

Addning @Rauno56 and @MSNev to approvers

internal: add missing approvers from core

---

src/api/trace.ts
test/api/api.test.ts

Set the new TracerProvider as delegate in ProxyTracerProvider only if global registration was successful.
fixes: https://github.com/open-telemetry/opentelemetry-js-api/issues/104

fix: set delegate after successful registration

---

.github/workflows/lint.yaml

Since the changelog is now autogenerated by release-please (example here: https://github.com/open-telemetry/opentelemetry-js-api/pull/120/files) there is no need to lint it.

chore: do not lint changelog

---

tsconfig.json

Related to:
- https://github.com/open-telemetry/opentelemetry-js/pull/2488
- https://github.com/open-telemetry/opentelemetry-js/issues/1887
Looking to remove all of the warnings about missing source maps

Add source map files to builds

---

.github/CODEOWNERS

So that we don't have to update the CODEOWNERS file every time a person joins @open-telemetry/javascript-approvers.

chore: update codeowners to user groups
